version: 0.85.0
# path to audit log file to verify
audit_log_file: 

# Expected format of audit log file(s) that should be verified: plaintext, json or CEF
audit_log_file_format: plaintext

# path to list of audit log files to verify
audit_log_file_list: 

# don't fail validation if some audit logs cannot be opened
audit_log_missing_ok: false

# path to config
config_file: 

# debug mode (shows order of input files)
d: false

# dump config
dump_config: false

# Generate with yaml config markdown text file with descriptions of all args
generate_markdown_args_table: false

# Folder from which will be loaded keys
keys_dir: .acrakeys

# Logging format of this tool: plaintext, json or CEF
logging_format: plaintext

# Number of Redis database for keys
redis_db_keys: 0

# <host>:<port> used to connect to Redis
redis_host_port: 

# Password to Redis database
redis_password: 

# Connection string (http://x.x.x.x:yyyy) for loading ACRA_MASTER_KEY from HashiCorp Vault
vault_connection_api_string: 

# KV Secret Path (secret/) for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_secrets_path: secret/

# Path to CA certificate for HashiCorp Vault certificate validation
vault_tls_ca_path: 

# Path to client TLS certificate for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_tls_client_cert: 

# Path to private key of the client TLS certificate for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_tls_client_key: 

# Use TLS to encrypt transport with HashiCorp Vault
vault_tls_transport_enable: false

