version: 0.90.0
# path to config
config_file: 

# Turn on debug logging
d: false

# dump config
dump_config: false

# Auth file
file: configs/auth.keys

# Generate with yaml config markdown text file with descriptions of all args
generate_markdown_args_table: false

# Folder from which will be loaded keys
keys_dir: .acrakeys

# Password
password: 

# Remove user
remove: false

# Add/update password for user
set: false

# User
user: 

# Connection string (http://x.x.x.x:yyyy) for loading ACRA_MASTER_KEY from HashiCorp Vault
vault_connection_api_string: 

# KV Secret Path (secret/) for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_secrets_path: secret/

# Path to CA certificate for HashiCorp Vault certificate validation
vault_tls_ca_path: 

# Path to client TLS certificate for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_tls_client_cert: 

# Path to private key of the client TLS certificate for reading ACRA_MASTER_KEY from HashiCorp Vault
vault_tls_client_key: 

# Use TLS to encrypt transport with HashiCorp Vault
vault_tls_transport_enable: false

